version: "3.8"
services:
  postgres:
    image: "postgres"
    env_file:
      - .env
    ports:
    - 54320:5432
    volumes:
    - database-data:/var/lib/postgresql/data/
  server:
    build:
      context: .
      dockerfile: timetables.Dockerfile
    env_file:
      - .env
    command: python timetables/manage.py runserver 0.0.0.0:8000
    ports:
    - "8000:8000"
    depends_on:
      - postgres
    volumes:
    - ./src:/app/src


volumes:
  database-data:

